version: '3'
services:
  oidc:
    container_name: oidc
    image: jboss/keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_USER: kcadmin
      KEYCLOAK_PASSWORD: admin

  nginx:
    container_name: nginx-oidc
    build:
      context: ./nginx
    ports:
      - "8081:8081"
      - "8082:80"
      - "8083:443"
    links:
      - "oidc:oidc"  # this hack is needed resolve oidc hostname